import { PERMISSIONS } from "./permissions";

export const ROLES = {
  ADMIN: "ADMIN",
  CDO: "CDO",
  DATA_STEWARD: "DATA_STEWARD",
  DATA_OWNER: "DATA_OWNER",
  DEVELOPER: "DEVELOPER",
  AUDITOR: "AUDITOR",
  ANALYST: "ANALYST",
  VIEWER: "VIEWER",
};

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: ALL_PERMISSIONS,
  [ROLES.CDO]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.JOBS_VIEW,
    PERMISSIONS.RULES_VIEW,
    PERMISSIONS.QUARANTINE_VIEW,
    PERMISSIONS.GOVERNANCE_VIEW,
    PERMISSIONS.COMPLIANCE_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.LINEAGE_VIEW,
    PERMISSIONS.STEWARDSHIP_VIEW,
  ],
  [ROLES.DATA_STEWARD]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.JOBS_VIEW,
    PERMISSIONS.RULES_VIEW,
    PERMISSIONS.RULES_MANAGE,
    PERMISSIONS.QUARANTINE_VIEW,
    PERMISSIONS.QUARANTINE_MANAGE,
    PERMISSIONS.STEWARDSHIP_VIEW,
  ],
  [ROLES.DATA_OWNER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.JOBS_VIEW,
    PERMISSIONS.GOVERNANCE_VIEW,
    PERMISSIONS.COMPLIANCE_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],
  [ROLES.DEVELOPER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.JOBS_VIEW,
    PERMISSIONS.JOBS_MANAGE,
    PERMISSIONS.RULES_VIEW,
    PERMISSIONS.LINEAGE_VIEW,
    PERMISSIONS.API_MONITOR_VIEW,
  ],
  [ROLES.AUDITOR]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.COMPLIANCE_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],
  [ROLES.ANALYST]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.JOBS_VIEW,
    PERMISSIONS.RULES_VIEW,
  ],
  [ROLES.VIEWER]: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.REPORTS_VIEW],
};

export function normalizeRole(role) {
  const value = String(role || "VIEWER").trim().toUpperCase();
  if (value === "STEWARD") return ROLES.DATA_STEWARD;
  if (value === "OWNER") return ROLES.DATA_OWNER;
  return ROLES[value] ? value : ROLES.VIEWER;
}

export function permissionsForRole(role) {
  return ROLE_PERMISSIONS[normalizeRole(role)] || ROLE_PERMISSIONS[ROLES.VIEWER];
}
